### ISSUE TITLE
Windows File Locking?

### ISSUE THREAD

**Issue by devdevgoat** [porglezomp-misc/live-reloading-rs#2]
When running the example on windows, I'm unable to update the library because it's 'in use by another program.'

Looking at [this comment](https://github.com/porglezomp-misc/live-reloading-rs/issues/1#issuecomment-362663814), my guess is windows isn't quite support atm?

**Comment by devdevgoat** [comment]
My work around, since I'm Windows 10 was to build and compile in WSL, incase anyone happens on this:

1.[Setup WSL and vscode](https://code.visualstudio.com/docs/remote/wsl-tutorial) and add the following to your setting file:
```
{
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true,
        "**/target/**": true
    }
}
```
2. [Install rust](https://www.rust-lang.org/learn/get-started)
3. [Install linker](https://github.com/rust-lang/www.rust-lang.org/issues/1012)
4. Create a working dir and open in vs code
`mkdir rust`
`cd rust`
`code .`
5. Build tutorial
6. Add the following to your cargo.toml:
```
[lib]
crate-type = ["dylib"]
```

**Comment by pragmatrix** [comment]
And there is also [this fork](https://github.com/aaronjewell/live-reloading-rs), which copies the dll before it gets loaded. This seems to work well as far I can tell.
